<a href="https://colab.research.google.com/github/tasleemkhan-code/hyperparameter-tuning-ml/blob/main/HyperParameterTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = df.drop('species', axis=1)
y = df['species']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# **KNN Model**

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [12]:
model_knn.score(x_test, y_test)

1.0

# **SVM Model**

In [13]:
from sklearn.svm import SVC

In [14]:
model_svc = SVC(gamma='auto')

In [15]:
model_svc.fit(x_train, y_train)

SVC(gamma='auto')

In [16]:
model_svc.score(x_test, y_test)

1.0

# ***TIME TO USE GRID SEARCH CV***

In [17]:
from sklearn.model_selection import GridSearchCV

In [18]:
classifiers = GridSearchCV((model_svc), {
    'C' : [1, 10, 20],
    'kernel' : ['rbf', 'linear'],
}, cv=5, return_train_score=False)

In [19]:
classifiers.fit(x, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [20]:
classifiers.cv_results_

{'mean_fit_time': array([0.00240655, 0.00279031, 0.00291243, 0.00410948, 0.00856357,
        0.00581651]),
 'std_fit_time': array([0.00090442, 0.00104791, 0.0001935 , 0.00116483, 0.00246012,
        0.00077842]),
 'mean_score_time': array([0.00143595, 0.00208011, 0.00213022, 0.00581679, 0.00628781,
        0.0061655 ]),
 'std_score_time': array([5.62428165e-05, 8.58721641e-04, 1.62562760e-04, 2.91653442e-03,
        1.28665585e-03, 2.06788899e-03]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6], dtype=int32)}

In [21]:
results = pd.DataFrame(classifiers.cv_results_)

In [22]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002407,0.000904,0.001436,0.000056,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002790,0.001048,0.002080,0.000859,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002912,0.000193,0.002130,0.000163,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004109,0.001165,0.005817,0.002917,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.008564,0.002460,0.006288,0.001287,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.005817,0.000778,0.006166,0.002068,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6

In [23]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

# **Random Search CV**

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifiers_r = RandomizedSearchCV((model_svc), {
    'C' : [1, 10, 20, 30, 40, 50],
    'kernel' : ['rbf', 'linear'],
}, n_iter=4, cv=5, return_train_score=False)

In [26]:
classifiers_r.fit(x, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30, 40, 50],
                                        'kernel': ['rbf', 'linear']})

In [27]:
results= pd.DataFrame(classifiers_r.cv_results_)

In [28]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003089,0.000674,0.002141,0.000187,linear,40,"{'kernel': 'linear', 'C': 40}",1.000000,1.000000,0.900000,0.900000,1.0,0.96,0.048990,2
1,0.002959,0.000264,0.002751,0.000684,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.98,0.016330,1
2,0.003921,0.001764,0.005070,0.002129,rbf,50,"{'kernel': 'rbf', 'C': 50}",1.000000,0.966667,0.900000,0.933333,1.0,0.96,0.038873,2
3,0.003814,0.001818,0.002615,0.000548,rbf,40,"{'kernel': 'rbf', 'C': 40}",1.000000,0.966667,0.900000,0.933333,1.0,0.96,0.038873,2

In [29]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       40       linear             0.96
1        1       linear             0.98
2       50          rbf             0.96
3       40          rbf             0.96